name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build --build-tests
    - name: Test
      run: swift test --enable-code-coverage
    - name: Convert coverage report
      run: xcrun llvm-cov export -format="lcov" .build/debug/SolarTimePackageTests.xctest/Contents/MacOS/OTPKitPackageTests -instr-profile .build/debug/codecov/default.profdata > coverage.lcov
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
